### ISSUE TITLE
Cursor reset when clicking a moving input

### ISSUE THREAD

**Issue by charithreddyv** [hodgef/react-simple-keyboard#896] opened 2020-11-04 14:35 UTC
Problem with input, characters getting added at end  when edited [codesandbox](https://codesandbox.io/s/brave-river-4ez6r)
Steps to reproduce:

1. Enter some text in email input filed hit enter.
2. Enter password hit enter.
3. Choose between some characters  with mouse on email field and enter text it appends text at end .

Thanks In Advance

**Comment by hodgef** [comment] 2020-11-04 14:43
Hello @charithreddyv,

I was not able to reproduce this issue. Here's what I got:

![gif](https://user-images.githubusercontent.com/25509135/98125085-00076b00-1e82-11eb-8b3e-49f9e95679ed.gif)


Regards,
Francisco Hodge

**Comment by charithreddyv** [comment] 2020-11-04 17:25
@hodgef Thanks for the quick response,   please use this  [codesandbox](https://codesandbox.io/s/ts-react-simple-keybaord-jq66c) is the same example as above but in ts . i was able to reproduce it when use a half screen (by covering half screen) i am using this package on a electron app which will be half screen (minimized) by default 
![keyboard](https://user-images.githubusercontent.com/30048901/98144356-527f7080-1ef0-11eb-919f-335b19ee9e6a.png)

I am able to reproduce it by doing something like this on browser [app](https://jq66c.csb.app/)

When i try to add `i` in between `uu` it is getting appended at the end


Thank You In Advance

**Comment by hodgef** [comment] 2020-11-04 22:42
Hey @charithreddyv,

I cannot reproduce this on any of the links you've provided. Can you reproduce this in your browser?

If you see this issue only on Electron, can you provide an Electron test repo so I can verify?

Regards,
Francisco Hodge

**Comment by charithreddyv** [comment] 2020-11-05 06:42
Hai @hodgef ,
As weird as it way sound i am able to reproduce it on chrome and firefox when the email text field is scrolled up (blocked by view ) this thing happens on the same url i pasted earlier i adjusted chrome devtools so when keyboards pops and  it is moving the text field to the top .

![data](https://user-images.githubusercontent.com/30048901/98206433-e3d9fb80-1f5f-11eb-86c1-deaec23153ac.gif)

This gif must give you and idea what i am talking about,

Thank's again for very fast response .

**Comment by hodgef** [comment] 2020-11-05 23:21
Hey @charithreddyv, thank you for the additional details. I think this is a simple-keyboard bug. I'll fix it asap

**Comment by hodgef** [comment] 2020-11-06 01:59
Hello @charithreddyv,

After looking at this issue more closely, I think a potential fix for this edge case is probably not worth it.

Basically there were two issues in the sandbox:

1. `inputName` was being set to an empty string, which is not a supported value. I commented that part. (FYI: whenever `inputName` changes, the caret position is reset).

2. **Edge case:** When you click on your input, it goes off screen (as the keyboard appears) and the mouse is therefore released _outside_ of the input. simple-keyboard's caret position handler is called on _mouseup_ and checks if the target is an input (that's where it will get the caret position from). Since your input is now off screen, the mouseup target will be something else and caret position never updates.

A workaround for item #2 is to delay the opening of the keyboard to allow the mouseup to happen before the input moves. 

I could fix this internally but that would imply listening to all document mousedown and I don't think this edge case warrants it.

Here's the updated sandbox with workarounds added:
https://codesandbox.io/s/ts-react-simple-keybaord-forked-lkg4y?file=/src/index.tsx

Thanks,
Francisco Hodge

**Closed by hodgef** 2020-11-06 01:59 UTC
Labels: ⛔️ Won't Fix, 💥 Bug
