### ISSUE TITLE
caretPosition is always null when using 'email' type of an input

### ISSUE THREAD

**Issue by phen0menon** [hodgef/react-simple-keyboard#1176] opened 2021-05-04 20:47 UTC
**React-simple-keyboard version**
3.0.75

**Describe the bug**
After 24 hours of searching for the bug, I finally found it! If you use type="email" in the input, `caretPosition` will always be `null`. I do not know what this is related to, but it is a critical issue for me.

Codesandbox: https://codesandbox.io/s/react-simple-keyboard-demo-forked-655ue?file=/src/index.js

**Comment by hodgef** [comment] 2021-05-04 23:08
Hello @phen0menon,

Flagging this as a duplicate of #247. Please check out that issue for details.

Thanks!
Francisco Hodge

**Closed by hodgef** 2021-05-04 23:08 UTC
